### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by emschwartz** [matdehaast/ilp-settlement-xrp#1]
Can we publish this to NPM so we don't need to point people at this repo to install it?

Also, should this be moved to the `interledgerjs` org?

**Comment by matdehaast** [comment]
@emschwartz It is already in the interledgerjs repo https://github.com/interledgerjs/settlement-xrp

**Comment by emschwartz** [comment]
Do you want to archive this repo then or mark it as deprecated in case anyone comes across it? I found it because I was searching "ilp-settlement-xrp" and missed the `settlement-xrp` in `interledgerjs`
